# Generated by Django 3.2.7 on 2021-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210924_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, help_text="The user's password.", max_length=255, verbose_name='password'),
        ),
    ]
